<?php

namespace Database\Seeders;

use App\Models\Car;
use Illuminate\Database\Seeder;

class CarSeeder extends Seeder
{
    public function run(): void
    {
        $cars = [
            [
                'make'          => 'BMW',
                'model'         => 'M5 Competition',
                'year'          => 2022,
                'vin'           => 'WBHJE7C58NCC12345',
                'location'      => 'Алматы',
                'description'   => 'Отличное состояние, полная комплектация, один владелец.',
                'mileage'       => 15000,
                'color'         => 'Черный',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 4.4,
                'power_hp'      => 625,
                'image_url'     => 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
                'is_live'       => true,
                'is_top'        => true,
                'is_finished'   => false,
                'current_bid'   => 52500000,
                'starting_price'=> 45000000,
                'ends_at'       => now()->addDays(2),
            ],
            [
                'make'          => 'Mercedes',
                'model'         => 'G63 AMG',
                'year'          => 2023,
                'vin'           => 'WDC4632241X123456',
                'location'      => 'Астана',
                'description'   => 'Новый автомобиль, пробег 3000 км.',
                'mileage'       => 3000,
                'color'         => 'Белый',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 4.0,
                'power_hp'      => 585,
                'image_url'     => 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
                'is_live'       => true,
                'is_top'        => true,
                'is_finished'   => false,
                'current_bid'   => 89000000,
                'starting_price'=> 80000000,
                'ends_at'       => now()->addDays(3),
            ],
            [
                'make'          => 'Porsche',
                'model'         => '911 Turbo S',
                'year'          => 2022,
                'vin'           => 'WP0ZZZ99ZNS123456',
                'location'      => 'Алматы',
                'description'   => 'Спортивный пакет, керамические тормоза.',
                'mileage'       => 8000,
                'color'         => 'Красный',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 3.8,
                'power_hp'      => 650,
                'image_url'     => 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
                'is_live'       => true,
                'is_top'        => false,
                'is_finished'   => false,
                'current_bid'   => 115000000,
                'starting_price'=> 100000000,
                'ends_at'       => now()->addDays(1),
            ],
            [
                'make'          => 'Lamborghini',
                'model'         => 'Urus',
                'year'          => 2021,
                'vin'           => 'ZPBUA1ZL0MLA12345',
                'location'      => 'Алматы',
                'description'   => 'Суперкроссовер, карбоновый пакет.',
                'mileage'       => 22000,
                'color'         => 'Желтый',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 4.0,
                'power_hp'      => 650,
                'image_url'     => 'https://images.unsplash.com/photo-1621135802920-133df287f89c?w=800',
                'is_live'       => true,
                'is_top'        => true,
                'is_finished'   => false,
                'current_bid'   => 145000000,
                'starting_price'=> 130000000,
                'ends_at'       => now()->addDays(4),
            ],
            [
                'make'          => 'Aston Martin',
                'model'         => 'DB11 V12',
                'year'          => 2021,
                'vin'           => 'SCFRMFAV4MGT12345',
                'location'      => 'Алматы',
                'description'   => 'Британский Gran Tourer, полная история обслуживания.',
                'mileage'       => 18000,
                'color'         => 'Серебристый',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 5.2,
                'power_hp'      => 630,
                'image_url'     => 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800',
                'is_live'       => false,
                'is_top'        => false,
                'is_finished'   => true,
                'current_bid'   => 94000000,
                'starting_price'=> 85000000,
                'ends_at'       => now()->subDays(1),
            ],
            [
                'make'          => 'Toyota',
                'model'         => 'Land Cruiser 300',
                'year'          => 2023,
                'vin'           => 'JTMCV02J80D123456',
                'location'      => 'Шымкент',
                'description'   => 'Флагманский внедорожник, все опции.',
                'mileage'       => 5000,
                'color'         => 'Черный',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Дизель',
                'engine_volume' => 3.5,
                'power_hp'      => 415,
                'image_url'     => 'https://images.unsplash.com/photo-1594502184342-2e12f877aa73?w=800',
                'is_live'       => true,
                'is_top'        => false,
                'is_finished'   => false,
                'current_bid'   => 42000000,
                'starting_price'=> 38000000,
                'ends_at'       => now()->addDays(5),
            ],
            [
                'make'          => 'Tesla',
                'model'         => 'Model S Plaid',
                'year'          => 2022,
                'vin'           => '5YJSA1E68NF123456',
                'location'      => 'Астана',
                'description'   => 'Электрокар, запас хода 600 км, автопилот.',
                'mileage'       => 12000,
                'color'         => 'Белый',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Электро',
                'engine_volume' => 0.0,
                'power_hp'      => 1020,
                'image_url'     => 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800',
                'is_live'       => true,
                'is_top'        => false,
                'is_finished'   => false,
                'current_bid'   => 38000000,
                'starting_price'=> 32000000,
                'ends_at'       => now()->addDays(2),
            ],
            [
                'make'          => 'Rolls-Royce',
                'model'         => 'Ghost',
                'year'          => 2021,
                'vin'           => 'SCA664S54MUX12345',
                'location'      => 'Алматы',
                'description'   => 'Ультра-люкс седан, звездное небо на потолке.',
                'mileage'       => 9000,
                'color'         => 'Темно-синий',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 6.75,
                'power_hp'      => 571,
                'image_url'     => 'https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=800',
                'is_live'       => true,
                'is_top'        => true,
                'is_finished'   => false,
                'current_bid'   => 250000000,
                'starting_price'=> 220000000,
                'ends_at'       => now()->addDays(7),
            ],
            [
                'make'          => 'Audi',
                'model'         => 'RS7 Sportback',
                'year'          => 2022,
                'vin'           => 'WAUZZZ4H9NN123456',
                'location'      => 'Алматы',
                'description'   => 'Спортивный лифтбек, пакет Dynamic.',
                'mileage'       => 11000,
                'color'         => 'Серый',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 4.0,
                'power_hp'      => 600,
                'image_url'     => 'https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?w=800',
                'is_live'       => true,
                'is_top'        => false,
                'is_finished'   => false,
                'current_bid'   => 68000000,
                'starting_price'=> 60000000,
                'ends_at'       => now()->addDays(3),
            ],
            [
                'make'          => 'Bentley',
                'model'         => 'Bentayga',
                'year'          => 2022,
                'vin'           => 'SJAAC2ZV4NC123456',
                'location'      => 'Астана',
                'description'   => 'Люксовый SUV, массаж всех сидений.',
                'mileage'       => 14000,
                'color'         => 'Зеленый',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 4.0,
                'power_hp'      => 550,
                'image_url'     => 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=800',
                'is_live'       => true,
                'is_top'        => true,
                'is_finished'   => false,
                'current_bid'   => 175000000,
                'starting_price'=> 160000000,
                'ends_at'       => now()->addDays(6),
            ],
            [
                'make'          => 'Lexus',
                'model'         => 'LX 600',
                'year'          => 2023,
                'vin'           => 'JTJHM7FX4P4123456',
                'location'      => 'Алматы',
                'description'   => 'Топовая версия Ultra Luxury, 4 места.',
                'mileage'       => 7000,
                'color'         => 'Черный',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 3.5,
                'power_hp'      => 415,
                'image_url'     => 'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=800',
                'is_live'       => true,
                'is_top'        => false,
                'is_finished'   => false,
                'current_bid'   => 58000000,
                'starting_price'=> 52000000,
                'ends_at'       => now()->addDays(4),
            ],
            [
                'make'          => 'McLaren',
                'model'         => '720S',
                'year'          => 2020,
                'vin'           => 'SBM14DCA0LW123456',
                'location'      => 'Алматы',
                'description'   => 'Суперкар, карбоновое шасси, лифт передней оси.',
                'mileage'       => 6000,
                'color'         => 'Оранжевый',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 4.0,
                'power_hp'      => 720,
                'image_url'     => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
                'is_live'       => false,
                'is_top'        => false,
                'is_finished'   => true,
                'current_bid'   => 132000000,
                'starting_price'=> 120000000,
                'ends_at'       => now()->subDays(3),
            ],
            [
                'make'          => 'Land Rover',
                'model'         => 'Defender 110',
                'year'          => 2022,
                'vin'           => 'SALEH2RX0NA123456',
                'location'      => 'Атырау',
                'description'   => 'Внедорожник нового поколения, пневмоподвеска.',
                'mileage'       => 25000,
                'color'         => 'Хаки',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Дизель',
                'engine_volume' => 3.0,
                'power_hp'      => 300,
                'image_url'     => 'https://images.unsplash.com/photo-1598911215390-b04f1b7c1df4?w=800',
                'is_live'       => true,
                'is_top'        => false,
                'is_finished'   => false,
                'current_bid'   => 35000000,
                'starting_price'=> 30000000,
                'ends_at'       => now()->addDays(2),
            ],
            [
                'make'          => 'Porsche',
                'model'         => 'Cayenne Turbo GT',
                'year'          => 2022,
                'vin'           => 'WP1AG2AY0NDA12345',
                'location'      => 'Алматы',
                'description'   => 'Самый быстрый серийный SUV Porsche.',
                'mileage'       => 10000,
                'color'         => 'Черный',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 4.0,
                'power_hp'      => 640,
                'image_url'     => 'https://images.unsplash.com/photo-1580274455191-1c62238fa333?w=800',
                'is_live'       => true,
                'is_top'        => true,
                'is_finished'   => false,
                'current_bid'   => 98000000,
                'starting_price'=> 88000000,
                'ends_at'       => now()->addDays(5),
            ],
            [
                'make'          => 'Maserati',
                'model'         => 'MC20',
                'year'          => 2021,
                'vin'           => 'ZAM45VLA0M1123456',
                'location'      => 'Алматы',
                'description'   => 'Итальянский суперкар, двигатель Nettuno.',
                'mileage'       => 4000,
                'color'         => 'Синий',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 3.0,
                'power_hp'      => 630,
                'image_url'     => 'https://images.unsplash.com/photo-1612544448445-b8232cff3b6c?w=800',
                'is_live'       => true,
                'is_top'        => false,
                'is_finished'   => false,
                'current_bid'   => 110000000,
                'starting_price'=> 100000000,
                'ends_at'       => now()->addDays(3),
            ],
        ];

        foreach ($cars as $car) {
            Car::updateOrCreate(['vin' => $car['vin']], $car);
        }
    }
}