<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class FreshCarsSeeder extends Seeder
{
    public function run(): void
    {
        // Удаляем старые лоты и ставки
        DB::table('bids')->delete();
        DB::table('cars')->delete();
        DB::statement('ALTER TABLE cars AUTO_INCREMENT = 1');

        $now = Carbon::now();

        $cars = [
            [
                'make'          => 'BMW',
                'model'         => 'M5 Competition',
                'year'          => 2023,
                'vin'           => 'WBS83CH090ANE1001',
                'location'      => 'Алматы',
                'description'   => 'BMW M5 Competition в идеальном состоянии. Один владелец, полная сервисная история.',
                'mileage'       => 12000,
                'color'         => 'Чёрный сапфир',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 4.4,
                'power_hp'      => 625,
                'image_url'     => 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800',
                'is_live'       => 1,
                'is_top'        => 1,
                'is_finished'   => 0,
                'starting_price'=> 45000000,
                'current_bid'   => 45000000,
                'ends_at'       => $now->copy()->addDays(7),
            ],
            [
                'make'          => 'Mercedes-Benz',
                'model'         => 'G63 AMG',
                'year'          => 2023,
                'vin'           => 'WDB4632721X001002',
                'location'      => 'Алматы',
                'description'   => 'Mercedes G63 AMG. Легендарный внедорожник с мощью 585 л.с.',
                'mileage'       => 8500,
                'color'         => 'Обсидиан чёрный',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 4.0,
                'power_hp'      => 585,
                'image_url'     => 'https://images.unsplash.com/photo-1520031441872-265e4ff70366?w=800',
                'is_live'       => 1,
                'is_top'        => 1,
                'is_finished'   => 0,
                'starting_price'=> 85000000,
                'current_bid'   => 85000000,
                'ends_at'       => $now->copy()->addDays(6),
            ],
            [
                'make'          => 'Porsche',
                'model'         => '911 Turbo S',
                'year'          => 2022,
                'vin'           => 'WP0AD2A99NS001003',
                'location'      => 'Астана',
                'description'   => 'Porsche 911 Turbo S. Максимальная комплектация, керамические тормоза.',
                'mileage'       => 6200,
                'color'         => 'GT Серебристый',
                'transmission'  => 'PDK',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 3.8,
                'power_hp'      => 650,
                'image_url'     => 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
                'is_live'       => 1,
                'is_top'        => 0,
                'is_finished'   => 0,
                'starting_price'=> 95000000,
                'current_bid'   => 95000000,
                'ends_at'       => $now->copy()->addDays(5),
            ],
            [
                'make'          => 'Lamborghini',
                'model'         => 'Urus',
                'year'          => 2022,
                'vin'           => 'ZPBUA1ZL4NLA01004',
                'location'      => 'Алматы',
                'description'   => 'Lamborghini Urus — самый быстрый SUV в мире. Полная комплектация Pearl Capsule.',
                'mileage'       => 15000,
                'color'         => 'Bianco Icarus',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 4.0,
                'power_hp'      => 650,
                'image_url'     => 'https://images.unsplash.com/photo-1588258219511-64eb629cb833?w=800',
                'is_live'       => 1,
                'is_top'        => 1,
                'is_finished'   => 0,
                'starting_price'=> 120000000,
                'current_bid'   => 120000000,
                'ends_at'       => $now->copy()->addDays(8),
            ],
            [
                'make'          => 'Rolls-Royce',
                'model'         => 'Ghost',
                'year'          => 2022,
                'vin'           => 'SCA664S54NUX01005',
                'location'      => 'Алматы',
                'description'   => 'Rolls-Royce Ghost. Звёздное небо на потолке, массаж, вентиляция сидений.',
                'mileage'       => 9000,
                'color'         => 'Темно-синий',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 6.8,
                'power_hp'      => 571,
                'image_url'     => 'https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=800',
                'is_live'       => 1,
                'is_top'        => 1,
                'is_finished'   => 0,
                'starting_price'=> 220000000,
                'current_bid'   => 220000000,
                'ends_at'       => $now->copy()->addDays(9),
            ],
            [
                'make'          => 'Audi',
                'model'         => 'RS7 Sportback',
                'year'          => 2022,
                'vin'           => 'WAUZZZ4H9NN001006',
                'location'      => 'Астана',
                'description'   => 'Audi RS7 Sportback. Динамичный спортивный универсал с 600 л.с.',
                'mileage'       => 18000,
                'color'         => 'Нардо Грей',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 4.0,
                'power_hp'      => 600,
                'image_url'     => 'https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?w=800',
                'is_live'       => 1,
                'is_top'        => 0,
                'is_finished'   => 0,
                'starting_price'=> 55000000,
                'current_bid'   => 55000000,
                'ends_at'       => $now->copy()->addDays(4),
            ],
            [
                'make'          => 'Bentley',
                'model'         => 'Bentayga',
                'year'          => 2022,
                'vin'           => 'SCBCR53W8CC001007',
                'location'      => 'Алматы',
                'description'   => 'Bentley Bentayga — роскошный SUV. Мультимедиа Naim, панорамная крыша.',
                'mileage'       => 22000,
                'color'         => 'Белый',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 4.0,
                'power_hp'      => 550,
                'image_url'     => 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=800',
                'is_live'       => 1,
                'is_top'        => 0,
                'is_finished'   => 0,
                'starting_price'=> 130000000,
                'current_bid'   => 130000000,
                'ends_at'       => $now->copy()->addDays(6),
            ],
            [
                'make'          => 'McLaren',
                'model'         => '720S',
                'year'          => 2021,
                'vin'           => 'SBM14DCA0MW001008',
                'location'      => 'Алматы',
                'description'   => 'McLaren 720S Spider. Карбоновый кузов, активная аэродинамика.',
                'mileage'       => 7500,
                'color'         => 'Оранжевый',
                'transmission'  => 'SSG',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 4.0,
                'power_hp'      => 720,
                'image_url'     => 'https://images.unsplash.com/photo-1562591176-b4ac53c20f6c?w=800',
                'is_live'       => 1,
                'is_top'        => 1,
                'is_finished'   => 0,
                'starting_price'=> 110000000,
                'current_bid'   => 110000000,
                'ends_at'       => $now->copy()->addDays(7),
            ],
            [
                'make'          => 'Tesla',
                'model'         => 'Model S Plaid',
                'year'          => 2022,
                'vin'           => '5YJSA1E68NF001009',
                'location'      => 'Алматы',
                'description'   => 'Tesla Model S Plaid. 0-100 км/ч за 2.1 сек. Запас хода 628 км.',
                'mileage'       => 25000,
                'color'         => 'Жемчужно-белый',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Электро',
                'engine_volume' => 0.0,
                'power_hp'      => 1020,
                'image_url'     => 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800',
                'is_live'       => 1,
                'is_top'        => 0,
                'is_finished'   => 0,
                'starting_price'=> 38000000,
                'current_bid'   => 38000000,
                'ends_at'       => $now->copy()->addDays(5),
            ],
            [
                'make'          => 'Lexus',
                'model'         => 'LX 600',
                'year'          => 2023,
                'vin'           => 'JTJHY7AX4N4001010',
                'location'      => 'Астана',
                'description'   => 'Lexus LX 600 Ultra Luxury. 4 места, индивидуальные кресла сзади.',
                'mileage'       => 11000,
                'color'         => 'Чёрный',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 3.5,
                'power_hp'      => 415,
                'image_url'     => 'https://images.unsplash.com/photo-1621135802920-133df287f89c?w=800',
                'is_live'       => 1,
                'is_top'        => 0,
                'is_finished'   => 0,
                'starting_price'=> 65000000,
                'current_bid'   => 65000000,
                'ends_at'       => $now->copy()->addDays(10),
            ],
            [
                'make'          => 'Porsche',
                'model'         => 'Cayenne Turbo GT',
                'year'          => 2022,
                'vin'           => 'WP1AF2A9XNL001011',
                'location'      => 'Алматы',
                'description'   => 'Porsche Cayenne Turbo GT. Самый быстрый Cayenne в истории. Трек-пакет.',
                'mileage'       => 9500,
                'color'         => 'Карбон Чёрный',
                'transmission'  => 'PDK',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 4.0,
                'power_hp'      => 640,
                'image_url'     => 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800',
                'is_live'       => 1,
                'is_top'        => 1,
                'is_finished'   => 0,
                'starting_price'=> 105000000,
                'current_bid'   => 105000000,
                'ends_at'       => $now->copy()->addDays(8),
            ],
            [
                'make'          => 'Maserati',
                'model'         => 'MC20',
                'year'          => 2022,
                'vin'           => 'ZAM45VLA4N1001012',
                'location'      => 'Алматы',
                'description'   => 'Maserati MC20 — итальянский суперкар. Мотор Nettuno 630 л.с.',
                'mileage'       => 4200,
                'color'         => 'Bianco Audace',
                'transmission'  => 'DCT',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 3.0,
                'power_hp'      => 630,
                'image_url'     => 'https://images.unsplash.com/photo-1612544448445-b8232cff3b6c?w=800',
                'is_live'       => 1,
                'is_top'        => 1,
                'is_finished'   => 0,
                'starting_price'=> 125000000,
                'current_bid'   => 125000000,
                'ends_at'       => $now->copy()->addDays(6),
            ],
            [
                'make'          => 'Land Rover',
                'model'         => 'Defender 110',
                'year'          => 2023,
                'vin'           => 'SALCA2AX4NH001013',
                'location'      => 'Алматы',
                'description'   => 'Land Rover Defender 110 X. Полный привод, пневмоподвеска, панорама.',
                'mileage'       => 14000,
                'color'         => 'Тёмно-зелёный',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 3.0,
                'power_hp'      => 400,
                'image_url'     => 'https://images.unsplash.com/photo-1519245659620-e859806a8d3b?w=800',
                'is_live'       => 1,
                'is_top'        => 0,
                'is_finished'   => 0,
                'starting_price'=> 48000000,
                'current_bid'   => 48000000,
                'ends_at'       => $now->copy()->addDays(7),
            ],
            [
                'make'          => 'Aston Martin',
                'model'         => 'DB11 V12',
                'year'          => 2021,
                'vin'           => 'SCFRMHAV4MGT01014',
                'location'      => 'Астана',
                'description'   => 'Aston Martin DB11 V12. Британский GT с атмосферным V12.',
                'mileage'       => 16000,
                'color'         => 'Midnight Blue',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 5.2,
                'power_hp'      => 630,
                'image_url'     => 'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800',
                'is_live'       => 1,
                'is_top'        => 0,
                'is_finished'   => 0,
                'starting_price'=> 90000000,
                'current_bid'   => 90000000,
                'ends_at'       => $now->copy()->addDays(5),
            ],
            [
                'make'          => 'Toyota',
                'model'         => 'Land Cruiser 300',
                'year'          => 2023,
                'vin'           => 'JTMHX3FJ5P4001015',
                'location'      => 'Алматы',
                'description'   => 'Toyota Land Cruiser 300 GR Sport. Редкая версия, полная комплектация.',
                'mileage'       => 19000,
                'color'         => 'Чёрный',
                'transmission'  => 'Автомат',
                'fuel_type'     => 'Бензин',
                'engine_volume' => 3.5,
                'power_hp'      => 415,
                'image_url'     => 'https://images.unsplash.com/photo-1559416523-140ddc3d238c?w=800',
                'is_live'       => 1,
                'is_top'        => 0,
                'is_finished'   => 0,
                'starting_price'=> 42000000,
                'current_bid'   => 42000000,
                'ends_at'       => $now->copy()->addDays(9),
            ],
        ];

        foreach ($cars as $car) {
            DB::table('cars')->insert(array_merge($car, [
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }

        $this->command->info('✅ ' . count($cars) . ' лотов создано!');
    }
}